### ISSUE TITLE
Modifications for Turbolinks

### ISSUE THREAD

**Issue by PericlesTheo** [gravityblast/component.js#1]
Finally managed to play around with it and it works really good. I thought about some modifications that can make life better when using it with Turbolinks and I'd like to hear your ideas.

Let's say you do some polling on the confirmation page that will tell the user if their booking has been accepted by the seller.

```
setTimeout(checkIfSellerResponded, 2000);
```

With Turbolinks on, visiting another page will still keep making that request. So it would be nice if along with the execution of the component, you could unmount it as well.

The components will need to change the way of registering a component. Instead of accepting the name of the component and a func, it will accept and object with the name, an `onMount` and an `unMount` function.

``` js
// component.js
(function (Components) {
  Components.register({name: 'the-name', onMount: sellerResponded, unMount: removePolling});
  ...
})(Components);
```

``` js
// components.js

Components = {
  ...
  register: function(component) {
    this.components[component.name] = component;
  },
  ...
}
```

Now that we have a way to unmount a component, each time we `Components.init` we can unmount them. What is left to do is to keep track of what components we have initialized on each `page:change`.

``` js
// components.js

Components = {
  components: {},
  initializedComponents: {}, // Keeps track of initializedComponents per page

  init: function () {
    var elements = $('[data-js-component]');
    // On each init, we unmount the initialized components
    this.unMountInitializedComponents(this.initializedComponents);
    ...
  },

  ...

  initializeComponent: function ($element, component) {
    ....
    component.onMount($element, options);
    // Adding it to the initialized collection
    this.initializedComponents[component.name] = component
  },

  unMountInitializedComponents: function (components) {
    for (component in components) {
     // a component does not need to define an unMount method. For example a Tabs component, doesn't need to be unmounted.
      if (components[component].unMount) {
        components[component].unMount();
      }
    }

    this.initializedComponents = {}; // We are resetting the initializedComponents
  }
}
```

WDYT?

**Comment by gravityblast** [comment]
@PericlesTheo I like the idea! should we unmount all the components or just the ones attached to elements replaced in the page? for example, if the component is attached to the `html` element, what should we do?
